### ISSUE TITLE
可以支持proxy吗

### ISSUE THREAD

**Issue by wisonli** [Shadownc/DDG-Chat-go#1]
如果可以支持proxy吗？那么可以方便部署。谢谢！

**Comment by Shadownc** [comment]
拉取最新代码重新部署即可

**Comment by wisonli** [comment]
> y吗？那么可以方便部署。谢谢！



> 拉取最新代码重新部署即可

不是这个意思。是比如我部署在中国，但是中国的ip是访问不了openai的，所以如果支持proxy，那么可以通过proxy支持访问openai。更多的用途是，如果openai屏蔽了我的vps的ip（比如我的vps的ip地址比较烂），那么我可以通过warp的方式访问openai，这样也是需要支持proxy。

**Comment by Shadownc** [comment]
不就是代理吗 有什么区别？你自己挂代理就好了呀 改一下代理地址

**Comment by wisonli** [comment]
> 不就是代理吗 有什么区别？你自己挂代理就好了呀 改一下代理地址

不好意思，我看到你已经更新了。配置了PROXY_URL参数。应该可以了吧，我重拉试试。谢谢！

**Comment by Shadownc** [comment]
我还以为我理解错了 拉最新的docker部署就行应该

**Comment by wisonli** [comment]
> 我还以为我理解错了 拉最新的docker部署就行应该

对的。已经测试了。完全正常工作。感谢感谢！！

**Comment by Shadownc** [comment]
给个Star就行 哈哈
